/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import formKlijent.FormNoviKlijent;
import formKlijent.FormPretragaKlijenta;
import formNajvrednijiAntikviteti.FormPregledAntikviteta;
import formRacun.FormPretragaRacuna;
import formUmetnickoDelo.FormNovoUmetnickoDelo;
import formUmetnickoDelo.FormPretragaUmetnickogDela;
import controller.ClientController;
import domain.Klijent;
import domain.Racun;
import domain.StavkaRacuna;
import domain.TipDela;
import domain.UmetnickoDelo;
import domain.Zaposleni;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import models.TableModelStavkeRacuna;
import session.Session;

/**
 *
 * @author Vojislav
 */
public class MainForm extends javax.swing.JFrame {

    Zaposleni z;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        Image logo = Toolkit.getDefaultToolkit().getImage("src/logoIkonica/logo.png");
        setIconImage(logo);
        tblStavke.setOpaque(true);
        tblStavke.setFillsViewportHeight(true);
        tblStavke.setBackground(new ColorUIResource(255, 235, 230));
        Color pozadina = new Color(231, 249, 255);
        getContentPane().setBackground(pozadina);
        setLocationRelativeTo(null);
        this.z = Session.getInstance().getUlogovani();
        String ulogovani = z.toString();
        lblUlogovani.setText("Trenutno ulogovani zaposleni: ");
        lblCekiraniUser.setText(ulogovani);
        lblCekiraniUser.setFont(new Font("Sans-Serif", Font.BOLD, 12));
        srediFormu();
        setTitle("Glavna forma");
        srediMeniIteme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbKlijent = new javax.swing.JComboBox();
        txtCenaBezPopusta = new javax.swing.JFormattedTextField();
        txtPopust = new javax.swing.JFormattedTextField();
        txtCenaSaPopustom = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbUmetnickoDelo = new javax.swing.JComboBox();
        txtKolicina = new javax.swing.JFormattedTextField();
        txtCena = new javax.swing.JFormattedTextField();
        btnObrisi = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cmbTipDela = new javax.swing.JComboBox();
        btnSacuvaj = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblCekiraniUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miNoviKlijent = new javax.swing.JMenuItem();
        miPretragaKlijenta = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miNovoUmetnickoDelo = new javax.swing.JMenuItem();
        miPretragaUmetnickihDela = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miPretragaRacuna = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        miNajvrednijiAntikviteti = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setBackground(new java.awt.Color(16, 24, 32));
        lblUlogovani.setForeground(new java.awt.Color(16, 24, 32));
        lblUlogovani.setText("Ulogovani");

        jPanel1.setBackground(new java.awt.Color(231, 249, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos racuna"));

        jLabel1.setText("Klijent:");

        jLabel2.setText("Ukupna cena (bez popusta):");

        jLabel3.setText("Popust:");

        jLabel4.setText("Ukupna cena (sa popustom):");

        cmbKlijent.setBackground(new java.awt.Color(255, 235, 230));
        cmbKlijent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbKlijent.setOpaque(true);
        cmbKlijent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbKlijentItemStateChanged(evt);
            }
        });

        txtCenaBezPopusta.setBackground(new java.awt.Color(149, 210, 236));
        txtCenaBezPopusta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCenaBezPopusta.setOpaque(true);

        txtPopust.setBackground(new java.awt.Color(149, 210, 236));
        txtPopust.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txtCenaSaPopustom.setBackground(new java.awt.Color(149, 210, 236));
        txtCenaSaPopustom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCenaSaPopustom.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(149, 210, 236));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Unos stavki", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 12), new java.awt.Color(16, 24, 32))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(16, 24, 32));
        jLabel5.setText("Umetnicko delo:");

        jLabel6.setForeground(new java.awt.Color(16, 24, 32));
        jLabel6.setText("Kolicina:");

        jLabel7.setForeground(new java.awt.Color(16, 24, 32));
        jLabel7.setText("Cena:");

        cmbUmetnickoDelo.setBackground(new java.awt.Color(255, 235, 230));
        cmbUmetnickoDelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUmetnickoDelo.setOpaque(true);
        cmbUmetnickoDelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUmetnickoDeloItemStateChanged(evt);
            }
        });
        cmbUmetnickoDelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbUmetnickoDeloMouseClicked(evt);
            }
        });

        txtKolicina.setBackground(new java.awt.Color(231, 249, 255));
        txtKolicina.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtKolicina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKolicinaKeyReleased(evt);
            }
        });

        txtCena.setBackground(new java.awt.Color(231, 249, 255));
        txtCena.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btnObrisi.setBackground(new java.awt.Color(231, 249, 255));
        btnObrisi.setText("Obrisi stavku");
        btnObrisi.setOpaque(true);
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnDodaj.setBackground(new java.awt.Color(231, 249, 255));
        btnDodaj.setText("Dodaj stavku");
        btnDodaj.setOpaque(true);
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        tblStavke.setBackground(new java.awt.Color(231, 249, 255));
        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        jLabel8.setForeground(new java.awt.Color(16, 24, 32));
        jLabel8.setText("Tip dela:");

        cmbTipDela.setBackground(new java.awt.Color(255, 235, 230));
        cmbTipDela.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipDela.setOpaque(true);
        cmbTipDela.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTipDelaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbUmetnickoDelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtKolicina)
                            .addComponent(txtCena)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDodaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(cmbTipDela, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbTipDela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbUmetnickoDelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisi)
                    .addComponent(btnDodaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvaj.setBackground(new java.awt.Color(231, 249, 255));
        btnSacuvaj.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        btnSacuvaj.setText("Sacuvaj racun");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbKlijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCenaBezPopusta)
                                    .addComponent(txtPopust)
                                    .addComponent(txtCenaSaPopustom))
                                .addContainerGap())))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCenaBezPopusta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPopust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCenaSaPopustom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel9.setText("jLabel9");

        lblCekiraniUser.setText("UserPng");
        lblCekiraniUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        jMenuBar1.setBackground(new java.awt.Color(255, 235, 230));

        jMenu6.setText("Klijent");

        miNoviKlijent.setText("Novi klijent");
        miNoviKlijent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviKlijentActionPerformed(evt);
            }
        });
        jMenu6.add(miNoviKlijent);

        miPretragaKlijenta.setText("Pretraga klijenta");
        miPretragaKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaKlijentaActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaKlijenta);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Umetnicko delo");

        miNovoUmetnickoDelo.setText("Novo umetnicko delo");
        miNovoUmetnickoDelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNovoUmetnickoDeloActionPerformed(evt);
            }
        });
        jMenu7.add(miNovoUmetnickoDelo);

        miPretragaUmetnickihDela.setText("Pretraga umetnickih dela");
        miPretragaUmetnickihDela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaUmetnickihDelaActionPerformed(evt);
            }
        });
        jMenu7.add(miPretragaUmetnickihDela);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Racun");

        miPretragaRacuna.setText("Pretraga racuna");
        miPretragaRacuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaRacunaActionPerformed(evt);
            }
        });
        jMenu8.add(miPretragaRacuna);

        jMenuBar1.add(jMenu8);

        jMenu1.setText("Najvredniji antikviteti");

        miNajvrednijiAntikviteti.setText("Pregled antikviteta");
        miNajvrednijiAntikviteti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNajvrednijiAntikvitetiActionPerformed(evt);
            }
        });
        jMenu1.add(miNajvrednijiAntikviteti);

        jMenuBar1.add(jMenu1);

        jMenu9.setText("Odjava sa sistema");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu9.add(miOdjava);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUlogovani)
                        .addGap(0, 0, 0)
                        .addComponent(lblCekiraniUser)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUlogovani)
                    .addComponent(lblCekiraniUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNoviKlijentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviKlijentActionPerformed
        new FormNoviKlijent(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviKlijentActionPerformed

    private void miPretragaKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaKlijentaActionPerformed
        new FormPretragaKlijenta(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaKlijentaActionPerformed

    private void miNovoUmetnickoDeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNovoUmetnickoDeloActionPerformed
        new FormNovoUmetnickoDelo(this, true).setVisible(true);
    }//GEN-LAST:event_miNovoUmetnickoDeloActionPerformed

    private void miPretragaUmetnickihDelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaUmetnickihDelaActionPerformed
        new FormPretragaUmetnickogDela(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaUmetnickihDelaActionPerformed

    private void cmbTipDelaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTipDelaItemStateChanged
        if (cmbTipDela.getSelectedItem() == null) {
            return;
        }
        txtKolicina.setEnabled(true);

        TipDela td = (TipDela) cmbTipDela.getSelectedItem();

        popuniUmetnickaDela(td);

        UmetnickoDelo ud = (UmetnickoDelo) cmbUmetnickoDelo.getSelectedItem();
        if (ud.isUnikat()) {
            txtKolicina.setText("1");
            int kolicina = Integer.parseInt(txtKolicina.getText());
            txtCena.setText(String.valueOf(ud.getCena() * kolicina));
            txtKolicina.setEnabled(false);
            return;
        }

        txtKolicina.setText("");
        txtCena.setText("0.00");

    }//GEN-LAST:event_cmbTipDelaItemStateChanged

    private void txtKolicinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKolicinaKeyReleased

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {

            if (txtKolicina.getText().isEmpty()) {
                txtKolicina.setText("");
                txtCena.setText("0.00");
                return;
            }

            UmetnickoDelo ud = (UmetnickoDelo) cmbUmetnickoDelo.getSelectedItem();

            int kolicina = Integer.parseInt(txtKolicina.getText());

            txtCena.setText(String.valueOf(ud.getCena() * kolicina));

        } else {

            txtKolicina.setText("");
            txtCena.setText("0.00");

        }


    }//GEN-LAST:event_txtKolicinaKeyReleased

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if (txtKolicina.getText().isEmpty() || txtCena.getText().equals("0.00")) {
            JOptionPane.showMessageDialog(this, "Morate uneti kolicinu!");
            return;
        }

        cmbKlijent.setEnabled(false);

        int kolicina = Integer.parseInt(txtKolicina.getText());
        double cena = Double.parseDouble(txtCena.getText());
        UmetnickoDelo ud = (UmetnickoDelo) cmbUmetnickoDelo.getSelectedItem();

        StavkaRacuna sr = new StavkaRacuna(null, -1, kolicina, cena, ud);

        TableModelStavkeRacuna tm = (TableModelStavkeRacuna) tblStavke.getModel();

        ArrayList<StavkaRacuna> listaStavki = tm.getLista();
        for (StavkaRacuna stavkaRacuna : listaStavki) {
            if (stavkaRacuna.getUmetnickoDelo().getNaziv().equals(sr.getUmetnickoDelo().getNaziv())
                    && (stavkaRacuna.getUmetnickoDelo().isUnikat() && sr.getUmetnickoDelo().isUnikat())) {
                JOptionPane.showMessageDialog(null, "Ne mozete dodati isto unikatno delo na racun, \n ima samo 1 primerak!");
                return;

            }
        }

        tm.dodajStavku(sr);

        if (cmbUmetnickoDelo.getSelectedItem() == null) {
            return;
        }
        txtKolicina.setEnabled(true);

        if (ud.isUnikat()) {
            txtKolicina.setText("1");
            txtCena.setText(String.valueOf(ud.getCena() * kolicina));
            txtKolicina.setEnabled(false);

            double cenaBezPopusta = Double.parseDouble(txtCenaBezPopusta.getText());

            cenaBezPopusta += sr.getCenaStavke();

            txtCenaBezPopusta.setText(String.valueOf(cenaBezPopusta));

            double popust = Double.parseDouble(txtPopust.getText());

            txtCenaSaPopustom.setText(String.valueOf(cenaBezPopusta * (1 - (popust / 100))));

            return;
        } else {
            txtKolicina.setText("");
            txtCena.setText("0.00");
        }

        double cenaBezPopusta = Double.parseDouble(txtCenaBezPopusta.getText());

        cenaBezPopusta += sr.getCenaStavke();

        txtCenaBezPopusta.setText(String.valueOf(cenaBezPopusta));

        double popust = Double.parseDouble(txtPopust.getText());

        txtCenaSaPopustom.setText(String.valueOf(cenaBezPopusta * (1 - (popust / 100))));

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeRacuna tm = (TableModelStavkeRacuna) tblStavke.getModel();

            StavkaRacuna sr = tm.vratiStavku(row);

            tm.obrisiStavku(row);

            if (tm.getLista().isEmpty()) {
                cmbKlijent.setEnabled(true);
                txtCenaBezPopusta.setText("0.00");
                txtCenaSaPopustom.setText("0.00");
                return;
            }

            double cenaBezPopusta = Double.parseDouble(txtCenaBezPopusta.getText());

            cenaBezPopusta -= sr.getCenaStavke();

            txtCenaBezPopusta.setText(String.valueOf(cenaBezPopusta));

            double popust = Double.parseDouble(txtPopust.getText());

            txtCenaSaPopustom.setText(String.valueOf(cenaBezPopusta * (1 - (popust / 100))));

        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void cmbUmetnickoDeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUmetnickoDeloItemStateChanged
        if (cmbUmetnickoDelo.getSelectedItem() == null) {
            return;
        }
        txtKolicina.setEnabled(true);

        UmetnickoDelo ud = (UmetnickoDelo) cmbUmetnickoDelo.getSelectedItem();
        if (ud.isUnikat()) {
            txtKolicina.setText("1");
            int kolicina = Integer.parseInt(txtKolicina.getText());
            txtCena.setText(String.valueOf(ud.getCena() * kolicina));
            txtKolicina.setEnabled(false);
            return;
        } else {
            txtKolicina.setText("");
            txtCena.setText("0.00");
        }
    }//GEN-LAST:event_cmbUmetnickoDeloItemStateChanged

    private void cmbKlijentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbKlijentItemStateChanged

        if (cmbKlijent.getSelectedItem() == null) {
            return;
        }

        Klijent k = (Klijent) cmbKlijent.getSelectedItem();

        if (k.getStatus().equals("STANDARD")) {
            txtPopust.setText("0.00");
        }
        if (k.getStatus().equals("SILVER")) {
            txtPopust.setText("5.00");
        }
        if (k.getStatus().equals("GOLD")) {
            txtPopust.setText("10.00");
        }

    }//GEN-LAST:event_cmbKlijentItemStateChanged

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {

            double cenaBezPopusta = Double.parseDouble(txtCenaBezPopusta.getText());
            double popust = Double.parseDouble(txtPopust.getText());
            double cenaSaPopustom = Double.parseDouble(txtCenaSaPopustom.getText());
            Klijent k = (Klijent) cmbKlijent.getSelectedItem();

            TableModelStavkeRacuna tm = (TableModelStavkeRacuna) tblStavke.getModel();

            Racun r = new Racun(null, new Date(), cenaBezPopusta, popust, cenaSaPopustom, k, z, tm.getLista());

            ClientController.getInstance().addRacun(r);
            JOptionPane.showMessageDialog(this, "Sistem je kreirao racun.");
            srediFormu();
            cmbKlijent.setEnabled(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void miPretragaRacunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaRacunaActionPerformed
        new FormPretragaRacuna(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaRacunaActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed

        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite sa sistema?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            Login l = new Login();
            l.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miNajvrednijiAntikvitetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNajvrednijiAntikvitetiActionPerformed
        new FormPregledAntikviteta(this, true).setVisible(true);
    }//GEN-LAST:event_miNajvrednijiAntikvitetiActionPerformed

    private void cmbUmetnickoDeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbUmetnickoDeloMouseClicked
        if (cmbUmetnickoDelo.getSelectedItem() == null) {
            return;
        }
        txtKolicina.setEnabled(true);

        UmetnickoDelo ud = (UmetnickoDelo) cmbUmetnickoDelo.getSelectedItem();
        if (ud.isUnikat()) {
            txtKolicina.setText("1");
            int kolicina = Integer.parseInt(txtKolicina.getText());
            txtCena.setText(String.valueOf(ud.getCena() * kolicina));
            txtKolicina.setEnabled(false);
            return;
        } else {
            txtKolicina.setText("");
            txtCena.setText("0.00");
        }
    }//GEN-LAST:event_cmbUmetnickoDeloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbKlijent;
    private javax.swing.JComboBox cmbTipDela;
    private javax.swing.JComboBox cmbUmetnickoDelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCekiraniUser;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNajvrednijiAntikviteti;
    private javax.swing.JMenuItem miNoviKlijent;
    private javax.swing.JMenuItem miNovoUmetnickoDelo;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPretragaKlijenta;
    private javax.swing.JMenuItem miPretragaRacuna;
    private javax.swing.JMenuItem miPretragaUmetnickihDela;
    private javax.swing.JTable tblStavke;
    private javax.swing.JFormattedTextField txtCena;
    private javax.swing.JFormattedTextField txtCenaBezPopusta;
    private javax.swing.JFormattedTextField txtCenaSaPopustom;
    private javax.swing.JFormattedTextField txtKolicina;
    private javax.swing.JFormattedTextField txtPopust;
    // End of variables declaration//GEN-END:variables

    public void popuniKlijente() {

        try {
            ArrayList<Klijent> klijenti = ClientController.getInstance().getAllKlijent();

            cmbKlijent.removeAllItems();

            for (Klijent klijent : klijenti) {
                cmbKlijent.addItem(klijent);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void srediFormu() {
        popuniKlijente();
        popuniTipoveDela();
        txtCenaBezPopusta.setText("0.00");
        txtCenaSaPopustom.setText("0.00");
        txtCenaBezPopusta.setEnabled(false);
        txtPopust.setEnabled(false);
        txtCenaSaPopustom.setEnabled(false);
        txtCena.setText("0.00");
        txtCena.setEnabled(false);
        tblStavke.setModel(new TableModelStavkeRacuna());
        cmbTipDela.setSelectedIndex(0);
        cmbUmetnickoDelo.setSelectedIndex(0);
        ImageIcon pngUserChecked = new ImageIcon("src/logoIkonica/cekiraniUser.png");
        lblCekiraniUser.setIcon(pngUserChecked);

        if (cmbUmetnickoDelo.getSelectedItem() == null) {
            return;
        }
        txtKolicina.setEnabled(true);

        UmetnickoDelo ud = (UmetnickoDelo) cmbUmetnickoDelo.getSelectedItem();
        if (ud.isUnikat()) {
            txtKolicina.setText("1");
            int kolicina = Integer.parseInt(txtKolicina.getText());
            txtCena.setText(String.valueOf(ud.getCena() * kolicina));
            txtKolicina.setEnabled(false);
        } else {
            txtKolicina.setText("");
            txtCena.setText("0.00");
        }

    }

    public void popuniUmetnickaDela(TipDela td) {
        try {
            ArrayList<UmetnickoDelo> umetnickaDela = ClientController.getInstance().getAllUmetnickoDelo(td);

            cmbUmetnickoDelo.removeAllItems();

            for (UmetnickoDelo umetnickoDelo : umetnickaDela) {
                cmbUmetnickoDelo.addItem(umetnickoDelo);
            }

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void popuniTipoveDela() {

        try {
            ArrayList<TipDela> tipoviDela = ClientController.getInstance().getAllTipDela();

            cmbTipDela.removeAllItems();

            for (TipDela tipDela : tipoviDela) {
                cmbTipDela.addItem(tipDela);
            }

            popuniUmetnickaDela(tipoviDela.get(0));

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void srediMeniIteme() {
        ImageIcon dodajKorisnikaPng = new ImageIcon("src/logoIkonica/dodajKorisnika.png");
        miNoviKlijent.setIcon(dodajKorisnikaPng);
        
        ImageIcon lupaPretraga = new ImageIcon("src/logoIkonica/lupaPretraga.png");
        miPretragaKlijenta.setIcon(lupaPretraga);
        
        miPretragaRacuna.setIcon(lupaPretraga);
        
        miPretragaUmetnickihDela.setIcon(lupaPretraga);
        
        ImageIcon novoUmetnickoDeloPng = new ImageIcon("src/logoIkonica/novoUmetnickoDelo.png");
        miNovoUmetnickoDelo.setIcon(novoUmetnickoDeloPng);
        
        ImageIcon pregledAntikvitetaPng = new ImageIcon("src/logoIkonica/pregledAntikviteta.png");
        miNajvrednijiAntikviteti.setIcon(pregledAntikvitetaPng);
        
        ImageIcon logout = new ImageIcon("src/logoIkonica/logout.png");
        miOdjava.setIcon(logout);
        
    }


}
